[package]
name = "bt_localized_txt"
version = "0.1.2"
edition = "2024"
authors = ["calvarez <calvarez@bachuetech.biz>"]
description = "A high-performance localization system for managing multiple languages. It provides fast lookups and efficiently handles missing translations."
keywords = ["localization","i18n","l10n","internationalization", "translation" ]
categories = ["localization", "internationalization"]
repository = "https://github.com/bachuetech/bt_localized_txt.git"
readme = "README.md"
homepage = "https://github.com/bachuetech/bt_localized_txt"
license = "GPL-3.0-only"

[dependencies]
bt_any_error = "0.1.0"
bt_logger = "0.6.0"
rustc-hash = "2.1.3"
toml = "1.1.4"
